os: linux
arch: arm64-graviton2
language: php
env:
  global:
    - DRUPAL_VERSION=7.78
  jobs:
    - TESTS=Actions,AJAX,Block,Book,Bootstrap,Cache,Color,Comment,Contextual,Dashboard,DBLog,File,Filter,Forum,Help,Locale,Mail,Menu
    - TESTS=Aggregator,Block,Contact,Database,Image,OpenID,Node,Search,Statistics,SimpleTest
    - TESTS=Pager,Path,PHP,Poll,RDF,Session,Shortcut,Syslog
    - TESTS=System,Taxonomy,Theme,Tracker,Translation,Trigger,Update,User,XML-RPC
#   - TESTS_WITH_SPACES="Entity API,Batch API,Field API,Field types,Field UI,File API,File API (remote),Form API,Path API"
php:
  - '7.1'
before_install:
  - cd ..
  - git clone https://GitHub.com/Beakerboy/DrupalSqlSrvCI.git DrupalCI
install:
  - bash DrupalCI/src/travis/install.sh
  - export PATH="/opt/mssql-tools/bin:$PATH"
before_script:
  - bash DrupalCI/src/travis/build.sh
  - cd drupal-project
  - wget https://git.drupalcode.org/issue/drupal-3215724/-/raw/7.x/scripts/run-tests.sh
  - rm scripts/run-tests.sh
  - cp run-tests.sh scripts/run-tests.sh
  - phpenv config-add ../sqlsrv/dev/travis/travis-7.x.ini
script:
  - php ./scripts/run-tests.sh --verbose --fail-only --php `which php` $TESTS
