language: php

php:
  - '7.3'

before_install:
  # Use pcov instead of xdebug
  - phpenv config-rm xdebug.ini
  - pecl channel-update pecl.php.net
  #- pecl install pcov
  # Install SQL Server for Linux
  - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2019.list)"
  - sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/prod.list)"
  - sudo apt-get update
  - sudo ACCEPT_EULA=Y apt-get install -y mssql-server mssql-tools unixodbc-dev
  - export MSSQL_SA_PASSWORD=Password12!
  - export ACCEPT_EULA=Y
  - export MSSQL_PID=Evaluation
  - sudo /opt/mssql/bin/mssql-conf setup
  - /opt/mssql-tools/bin/sqlcmd -P Password12! -S localhost -U SA -Q 'CREATE DATABASE mydrupalsite COLLATE Latin1_General_CI_AI '
  # Install the pdo_sqlsrv extension
  - sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17 unixodbc-dev gcc g++ make autoconf libc-dev pkg-config
  - pecl install sqlsrv
  - pecl install pdo_sqlsrv
  - phpenv config-add install/travis-7.x.ini
install:
  # Create a Drupal Site
  - cd ..
  - composer -n create-project drupal/recommended-project:^9.0@dev drupal
  - cd drupal
  - composer require drush/drush
  - export COMPOSER_MEMORY_LIMIT=-1
  - cp -r $TRAVIS_BUILD_DIR/drivers ./web/drivers
  - ls -al ./web
  - cp -rf $TRAVIS_BUILD_DIR ./web/modules/sqlsrv
  - PATH=$PATH:$TRAVIS_BUILD_DIR/../drupal/vendor/bin
  - drush site:install --db-url sqlsrv://sa:Password12!@localhost/mydrupalsite --db-su sa --db-su-pw Password12! -n
  # Install REGEX CLR
  - sudo apt-get install -qq mono-complete
  - cd $TRAVIS_BUILD_DIR/tests
  - mcs -reference:System.Data.dll -target:library -out:RegEx.dll regex.cs
  - sudo mv RegEx.dll /var/opt/mssql/data/
  - /opt/mssql-tools/bin/sqlcmd -P Password12! -S localhost -U SA -d mydrupalsite -Q "EXEC sp_configure 'show advanced options', 1; RECONFIGURE; EXEC sp_configure 'clr strict security', 0; RECONFIGURE; EXEC sp_configure 'clr enable', 1; RECONFIGURE"
  - /opt/mssql-tools/bin/sqlcmd -P Password12! -S localhost -U SA -d mydrupalsite -Q "CREATE ASSEMBLY Regex from '/var/opt/mssql/data/RegEx.dll' WITH PERMISSION_SET = SAFE"
  - /opt/mssql-tools/bin/sqlcmd -P Password12! -S localhost -U SA -d mydrupalsite -Q "CREATE FUNCTION dbo.REGEXP(@pattern NVARCHAR(100), @matchString NVARCHAR(100)) RETURNS bit EXTERNAL NAME Regex.RegExCompiled.RegExCompiledMatch"
  - cd $TRAVIS_BUILD_DIR/../drupal-project
  - cp $TRAVIS_BUILD_DIR/tests/phpunit.xml.dist web/core/phpunit.xml
  #- phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/../drupal-project/vendor/drupal/coder/coder_sniffer
  - cd web
  # Install core patches
  - wget https://www.drupal.org/files/issues/2019-05-28/2867788-53.patch
  - wget https://www.drupal.org/files/issues/2020-02-14/drupal-3113403-Make_condition_driver_overridable-14.patch
  - git apply 2867788-53.patch
  - git apply drupal-3113403-Make_condition_driver_overridable-14.patch
  # Install patches for tests
  - wget https://www.drupal.org/files/issues/2020-01-30/drupal-3108540-deprecationErrors-3.patch
  - wget https://www.drupal.org/files/issues/2020-02-05/drupal-3111134-database_specific_types-3.patch
  - git apply drupal-3108540-deprecationErrors-3.patch
  - git apply drupal-3111134-database_specific_types-3.patch
  - cd ..
script:
  #- pcov clobber
  - cd web
  - ../vendor/bin/phpunit -c core/phpunit.xml --testsuite=database,entity,sqlsrv
  # --coverage-clover $TRAVIS_BUILD_DIR/build/logs/clover.xml
  #- phpcs --standard=Drupal  modules/contrib/sqlsrv
after_success:
  - cd $TRAVIS_BUILD_DIR
  #- cat ./build/logs/clover.xml
  - sed -i 's/drupal\-project\/web\/modules\/contrib\///g' ./build/logs/clover.xml
  - sed -i 's/drupal\-project\/web/sqlsrv/g' ./build/logs/clover.xml
  - php-coveralls -v
