os: linux
arch: arm64-graviton2
language: php
# Functional and Unit tests require Apache
env:
  - DBVERSION=mssql2019 DB_COLLATION=LATIN1_GENERAL_100_CI_AS_SC_UTF8 DRUPAL_VERSION=7.78 TEST_SUITE=sqlsrv

php:
  - '7.1'

install:
  - cd ..
  - git clone https://github.com/Beakerboy/DrupalSqlSrvCI.git DrupalCI
  - bash DrupalCI/src/travis/install.sh
before_script:
  - bash DrupalCI/src/travis/build.sh
  # Replace the downloaded driver with this one.
  - rm -rf drupal-project/sites/all/modules/sqlsrv
  - cp -R sqlsrv drupal-project/sites/all/modules
  - rm -rf drupal-project/includes/database/sqlsrv
  - cp -R sqlsrv/sqlsrv drupal-project/includes/database
  - cd drupal-project
script:
  - php ./scripts/run-tests.sh --php `which php` -all
