
services:
  - mssql2016
image:
  - Visual Studio 2015
build:
  - ps: Invoke-Sqlcmd -Query "CREATE DATABASE mydrupalsite" -ConnectionString "(local)\SQL2016;Database=master;User ID=sa;Password=Password12!"
