services:
  - mssql2016
  #- iis
image:
  - Visual Studio 2017
environment:
  matrix:
    - TEST_SUITE: sqlsrv
      TEST_INDEX: 0
install:
  # Set up the Environment
  - cmd: mkdir c:\testlogs
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/Beakerboy/drupal-sqlsrv-regex/releases/download/1.0/RegEx.dll', 'C:\testlogs\RegEx.dll')
    # SET UP PHP
  - ps: choco install php --version=7.1.33 --package-parameters="/InstallDir:C:\tools\php" -y --no-progress 2>&1 > C:\TestLogs\choco_install_php.txt
  - ps: choco install urlrewrite -y --no-progress 2>&1 > C:\testlogs\choco_install_urlrewrite.txt
  - ps: |
      $cli = New-Object Net.WebClient
      $cli.Headers['User-Agent'] = 'Appveyor';
      $cli.DownloadFile('https://windows.php.net/downloads/pecl/releases/pdo_sqlsrv/5.6.1/php_pdo_sqlsrv-5.6.1-7.1-nts-vc14-x64.zip', 'C:\testlogs\php_pdo_sqlsrv.zip')
  - ps: Expand-Archive -Path 'C:\testlogs\php_pdo_sqlsrv.zip' -Destinationpath 'C:\testlogs\php_pdo_sqlsrv'
  - cmd: copy C:\testlogs\php_pdo_sqlsrv\php_pdo_sqlsrv.dll C:\tools\php\ext
  - ps: |
      $cli = New-Object Net.WebClient
      $cli.Headers['User-Agent'] = 'Appveyor';
      $cli.DownloadFile('http://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/php_wincache-2.0.0.8-7.1-nts-vc14-x64.zip', 'C:\testlogs\php_wincache.zip')
  - ps: Expand-Archive -Path 'C:\testlogs\php_wincache.zip' -Destinationpath 'C:\testlogs\php_wincache'
  - cmd: copy C:\testlogs\php_wincache\php_wincache.dll C:\tools\php\ext
  # Start Windows Update service
  - cmd: sc config wuauserv start= auto
  - cmd: net start wuauserv
  # Add php binary to PATH
  - ps: $Env:Path = "C:\tools\php;" + $Env:Path;
  # Edit the php.ini file.
  - cmd: type C:\tools\php\php.ini %APPVEYOR_BUILD_FOLDER%\dev\appveyor\php.ini > C:\tools\php\php.ini
  # Install Composer
  - ps: new-item c:\composer -itemtype directory
  - cmd: cd /d C:\composer
  - cmd: choco install composer -y
  - ps: refreshenv
  - cmd: SET PATH=C:\ProgramData\ComposerSetup\bin;%PATH%
  # Download Drupal
  - cmd: cd /d C:\inetpub\
  - cmd: mv wwwroot wwwroot-old
  - cmd: git clone https://git.drupalcode.org/project/drupal.git -b 7.x wwwroot
  - cmd: cd wwwroot
  - cmd: git checkout tags/7.60
  - cmd: cp %APPVEYOR_BUILD_FOLDER%\composer.json .
build_script:
  # For some reason this cannot go in the install potion of the appveyor config
  - cmd: sqlcmd -U sa -P Password12! -Q "CREATE DATABASE mydrupalsite"
  - cmd: sqlcmd -d mydrupalsite -U sa -P Password12! -Q "EXEC sp_configure 'show advanced options', 1; RECONFIGURE; EXEC sp_configure 'clr enable', 1; RECONFIGURE"
  - cmd: sqlcmd -d mydrupalsite -U sa -P Password12! -Q "CREATE ASSEMBLY Regex from 'C:\testlogs\RegEx.dll' WITH PERMISSION_SET = SAFE"
  - cmd: sqlcmd -d mydrupalsite -U sa -P Password12! -Q "CREATE FUNCTION dbo.REGEXP(@pattern NVARCHAR(100), @matchString NVARCHAR(100)) RETURNS bit EXTERNAL NAME Regex.RegExCompiled.RegExCompiledMatch"
  # Set up Drupal
  - cmd: cd /d C:\inetpub\wwwroot
  # Apply any pre-composer patches
  - cmd: set COMPOSER_MEMORY_LIMIT=-1
  - cmd: composer install -q
  # Add composer installed binaries to PATH
  - cmd: SET PATH=C:\inetpub\wwwroot\vendor\bin;%PATH%
  # Install other composer packages for production
  # Copy in the module
  - cmd: xcopy /S /I /E /Y /Q %APPVEYOR_BUILD_FOLDER% C:\inetpub\wwwroot\sites\all\modules\contrib\sqlsrv
  - cmd: xcopy /S /I /E /Y /Q %APPVEYOR_BUILD_FOLDER%\sqlsrv C:\inetpub\wwwroot\includes\database\sqlsrv
  - cmd: mkdir C:\inetpub\wwwroot\sites\default\files
  - cmd: mkdir C:\inetpub\wwwroot\sites\default\files\tmp
  # install wincache module
  - ps: (New-Object Net.WebClient).DownloadFile('https://ftp.drupal.org/files/projects/wincachedrupal-7.x-2.1.zip', 'C:\testlogs\wincachedrupal-7.x.zip')
  - ps: Expand-Archive -Path 'C:\testlogs\wincachedrupal-7.x.zip' -Destinationpath 'C:\inetpub\wwwroot\sites\all\modules\contrib'
  # Should we use recursive instead?
  - ps: |
      $sharepath = "C:\inetpub\wwwroot\sites"
      $Acl = Get-ACL $SharePath
      $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule("everyone","FullControl","ContainerInherit,Objectinherit","none","Allow")
      $Acl.AddAccessRule($AccessRule)
      Set-Acl $SharePath $Acl
  # Core Patches
  # Testing Patches
before_test:
  - cmd: cp %APPVEYOR_BUILD_FOLDER%\dev\appveyor\settings.php C:\inetpub\wwwroot\sites\default\
  - cmd: mkdir .\build\logs
  - cmd: drush si -y --db-url= sqlsrv://sa:Password12!@localhost/mydrupalsite --clean-url=0 --account-name=admin --account-pass=drupal --account-mail=admin@example.com
test_script:
  - cmd: cd C:\inetpub\wwwroot
  - cmd: php scripts\run-tests.sh --list --php C:\Tools\php\php.exe
