version: 1.0.{build}
skip_tags: true
init:
- ps: 
services:
- mssql2017
- iis
install:
  - ps: Set-Service 'SQLAgent$SQL2017' -StartupType Manual
  - ps: new-item c:\tools\php\ext -itemtype directory
  - ps: new-item c:\tmp -itemtype directory
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/microsoft/msphpsql/releases/download/v5.6.0/Windows-7.1.zip','c:\tmp\sqlsrv.zip')
  - ps: Expand-Archive -LiteralPath c:\tmp\sqlsrv.zip -DestinationPath c:\tmp
  - cmd: copy /Y c:\tmp\Windows-7.1\x64\php_pdo_sqlsrv_71_nts.dll c:\tools\php\ext\php_pdo_sqlsrv.dll
  - ps: (Get-Item c:\tools\php\ext\php_pdo_sqlsrv.dll).VersionInfo
  - cmd: rmdir c:\tmp /s /q
  - ps: new-item c:\tmp -itemtype directory
  - ps: (New-Object Net.WebClient).DownloadFile('http://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/php_wincache-2.0.0.8-7.1-nts-vc14-x64.zip','c:\tmp\wincache.zip')
  - ps: (new-object -com shell.application).namespace('C:\tmp').CopyHere((new-object -com shell.application).namespace('C:\tmp\wincache.zip').Items(),16)
  - cmd: dir c:\tmp
  - cmd: copy /-Y c:\tmp\php_wincache.dll c:\tools\php\ext\ 
  - ps: (Get-Item c:\tools\php\ext\php_wincache.dll).VersionInfo
  - ps: cinst -y OpenSSL.Light
  - ps: SET PATH=C:\Program Files\OpenSSL;%PATH%
  - ps: sc config wuauserv start= auto
  - ps: net start wuauserv
  - ps: cinst -y --allow-empty-checksums php -version 7.0.9
  - ps: cd c:\tools\php
  - ps:  Add-Content php.ini-production "'ndate.timezone=\"UTC\""
  - ps: Add-Content php.ini-production "'nextension_dir=ext"
  - ps: Add-Content php.ini-production "'nextension=php_openssl.dll"
  - ps: Add-Content php.ini-production "'nextension=php_wincache.dll"
  - ps: Add-Content php.ini-production "'nextension=php_pdo_sqlsrv.dll"
  - ps: Add-Content php.ini-production "'nextension=php_com_dotnet.dll"
  - ps: Add-Content php.ini-production "'nextension=php_sockets.dll"
  - ps: Add-Content php.ini-production "'nextension=php_mbstring.dll"
  - ps: Add-Content php.ini-production "'nextension=php_soap.dll"
  - ps: Add-Content php.ini-production "'nextension=php_curl.dll"
  - ps: Add-Content php.ini-production "'nextension=php_gd2.dll"
  - ps: Add-Content php.ini-production "'nextension=php_gettext.dll"
  - ps: Add-Content php.ini-production "'nzend_extension=php_opcache.dll"
  - ps: Add-Content php.ini-production "'nopcache.enable=1"
  - ps: Add-Content php.ini-production "'nopcache.enable_cli=1"
  - ps: Add-Content php.ini-production "'nopcache.memory_consumption=128"
  - ps: Add-Content php.ini-production "'nopcache.revalidate_freq=1500"
  - ps: Add-Content php.ini-production "'nopcache.max_accelerated_files=8000"
  - ps: Add-Content php.ini-production "'nwincache.ucenabled=1"
  - ps: Add-Content php.ini-production "'nwincache.ucachesize=128"
  - ps: Add-Content php.ini-production "'nwincache.fcenabled=0"
  - ps: Add-Content php.ini-production "'nrealpath_cache_size=5M"
  - ps: Add-Content php.ini-production "'nrealpath_cache_ttl=1800"
  - ps: Add-Content php.ini-production "'npdo_sqlsrv.client_buffer_max_kb_size=24480"
  - ps: copy php.ini-production php.ini
  - ps: echo Setup certificate store
  - ps: (New-Object Net.WebClient).DownloadFile('https://curl.haxx.se/ca/cacert.pem','C:\tmp\cacert.pem')
  - ps: Add-Content php.ini "'ncurl.cainfo=\"C:\\tmp\\cacert.pem\""
  - ps: SET PATH=C:\tools\php;%PATH%
  - ps: ($env:Path)
  - ps: new-item c:\composer -itemtype directory
  - ps: cd /d C:\composer
  - ps: php -r "readfile('http://getcomposer.org/installer');" | php
  - ps: (Get-Item C:\composer\composer.phar).length
  - ps: "'@php C:\\composer\\composer.phar ' + $([char]37) + '*' | Out-File C:\\composer\\composer.bat -Encoding ASCII"
  - ps: SET PATH=C:\composer;%PATH%
  - ps: cd /d C:\projects\
  - ps: composer create-project -n drupal-composer/drupal-project:8.x-dev
  - ps: cd /d C:\projects\drupal-project
  - ps: composer config repositories.drupal composer https://packages.drupal.org/8
  - ps: composer require drupal/sqlsrv:~1.0
  - ps: xcopy /S /I /E %cd%\web\modules\contrib\sqlsrv\drivers %cd%\web\drivers
  - ps: "'@php %cd%\\vendor\\drupal\\console\\bin\\drupal ' + $([char]37) + '*' | Out-File %cd%/web/drupal.bat -Encoding ASCII"
  - ps: cd /d C:\projects\drupal-project\web
  - ps: drupal about
  - ps: drupal site:install standard --langcode="en" --db-type="sqlsrv" --db-host="localhost\SQL2014" --db-name="mydrupalsite" --db-user="sa" --db-pass="Password12!" --db-port="1433" --site-name="SQL Server Drupal Site" --site-mail="admin@example.com" --account-name="admin" --account-mail="admin@example.com" --account-pass="admin" --no-interaction
  - ps: drupal about
  - ps: cd /d C:\projects\drupal-project
  - ps: cd /d C:\projects\drupal-project\web
  - ps: drupal module:install simpletest
  - ps: choco install -y urlrewrite
  - ps: New-WebSite -Name 'MyWebsite' -PhysicalPath 'c:\projects\drupal-project\web' -Force
  - ps: echo 127.0.0.1 www.mysite.com >> %WINDIR%\System32\Drivers\Etc\Hosts
  - ps: Import-Module WebAdministration; Set-ItemProperty 'IIS:\Sites\MyWebsite' -name Bindings -value @{protocol='http';bindingInformation='*:80:www.mysite.com'}
  - ps: SET PATH=%systemroot%\system32\inetsrv\;%PATH%
  - ps: echo Change default anonymous user AUTH to ApplicationPool
  - ps: appcmd set config -section:anonymousAuthentication /username:"" --password
  - ps: echo Setup FAST-CGI configuration
  - ps: appcmd set config /section:system.webServer/fastCGI /+[fullPath='C:\tools\php\php-cgi.exe']
  - ps: echo Setup FACT-CGI handler
  - ps: appcmd set config /section:system.webServer/handlers /+[name='PHP-FastCGI',path='*.php',verb='*',modules='FastCgiModule',scriptProcessor='C:\tools\php\php-cgi.exe',resourceType='Either']
  - ps: iisreset
  - ps: NET START W3SVC
  - ps: wget http://www.mysite.com/
test_script:
- cmd: >-
    cd /d C:\projects\drupal-project
    mkdir c:\testresults\
    php web/core/scripts/run-tests.sh --php php --all --verbose --url "http://www.mysite.com/" --xml c:\testresults\
artifacts:
- path: c:\testresults
  name: Results
