# https://www.drupalonwindows.com/en/blog/continuous-integration-and-testing-drupal-appveyor
version: 1.0.{build}
skip_tags: true
init:
- ps: 
services:
- mssql2017
- iis
install:
  - ps: Set-Service 'SQLAgent$SQL2017' -StartupType Manual
  - ps: new-item c:\tools\php\ext -itemtype directory
  - ps: new-item c:\tmp -itemtype directory
  # Download Microsoft Drivers for PHP for SQL Server
  - ps: $cli=New-Object Net.WebClient;$cli.Headers['User-Agent'] = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)';$cli.DownloadFile('https://github.com/microsoft/msphpsql/releases/download/v5.6.0/Windows-7.1.zip','c:\tmp\sqlsrv.zip')
  # Unzip The Drivers
  - ps: Expand-Archive -LiteralPath c:\tmp\sqlsrv.zip -DestinationPath c:\tmp\sqlsrv
  # Download Wincache
  - ps: $cli=New-Object Net.WebClient;$cli.Headers['User-Agent'] = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)';$cli.DownloadFile('https://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/php_wincache-2.0.0.8-7.1-nts-vc14-x64.zip','c:\tmp\wincache.zip')
  # Unzip Wincache
  - ps: Expand-Archive -Path c:\tmp\wincache.zip -DestinationPath c:\tmp\wincache
  # Configure and start the Windows Update Managaer
  - cmd: sc config wuauserv start=auto
  - cmd: net start wuauserv
  # Download PHP
  - ps: $cli=New-Object Net.WebClient;$cli.Headers['User-Agent'] = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)';$cli.DownloadFile('https://windows.php.net/downloads/releases/php-7.1.33-Win32-VC14-x64.zip','c:\tmp\php.zip')
  - ps: Expand-Archive -Path c:\tmp\php.zip -DestinationPath c:\tools\php
  # Copy wincache and Database extensions to php extension directory
  - cmd: copy /Y c:\tmp\wincache\php_wincache.dll c:\tools\php\ext\
  - cmd: copy /Y c:\tmp\sqlsrv\Windows-7.1\x64\php_pdo_sqlsrv_71_nts.dll c:\tools\php\ext\php_pdo_sqlsrv.dll
  # Prove that file is there
  - ps: (Get-Item c:\tools\php\ext\php_pdo_sqlsrv.dll).VersionInfo
  # Make a copy of the production php.ini file to edit.
  - cmd: cd c:\tools\php
  - cmd: copy php.ini-production php.ini
  # Add custom changes to php.ini
  - ps: Add-Content php.ini 'error_log="C:\Windows\Temp\php_errors.log"'
  - ps: Add-Content php.ini "date.timezone=UTC"
  - ps: Add-Content php.ini 'extension_dir="C:\tools\php\ext\"'
  - ps: Add-Content php.ini "extension=php_openssl.dll"
  - ps: Add-Content php.ini "extension=php_wincache.dll"
  - ps: Add-Content php.ini "extension=php_pdo_sqlsrv.dll"
  - ps: Add-Content php.ini "extension=php_com_dotnet.dll"
  - ps: Add-Content php.ini "extension=php_sockets.dll"
  - ps: Add-Content php.ini "extension=php_mbstring.dll"
  - ps: Add-Content php.ini "extension=php_soap.dll"
  - ps: Add-Content php.ini "extension=php_curl.dll"
  - ps: Add-Content php.ini "extension=php_gd2.dll"
  - ps: Add-Content php.ini "extension=php_gettext.dll"
  - ps: Add-Content php.ini "zend_extension=php_opcache.dll"
  - ps: Add-Content php.ini "opcache.enable=1"
  - ps: Add-Content php.ini "opcache.enable_cli=1"
  - ps: Add-Content php.ini "opcache.memory_consumption=128"
  - ps: Add-Content php.ini "opcache.revalidate_freq=1500"
  - ps: Add-Content php.ini "opcache.max_accelerated_files=8000"
  - ps: Add-Content php.ini "wincache.ucenabled=1"
  - ps: Add-Content php.ini "wincache.ucachesize=128"
  - ps: Add-Content php.ini "wincache.fcenabled=0"
  - ps: Add-Content php.ini "realpath_cache_size=5M"
  - ps: Add-Content php.ini "realpath_cache_ttl=1800"
  - ps: Add-Content php.ini "pdo_sqlsrv.client_buffer_max_kb_size=24480"
  - cmd: echo Setup certificate store
  - ps: (New-Object Net.WebClient).DownloadFile('https://curl.haxx.se/ca/cacert.pem','C:\tmp\cacert.pem')
  - ps: Add-Content php.ini "curl.cainfo=C:\tmp\cacert.pem"
  # Install openssl 
  - cmd: cinst -y -r OpenSSL.Light
  - cmd: SET PATH=C:\Program Files\OpenSSL;%PATH%
  # print php.ini to screen
  - ps: Get-Content c:\tools\php\php.ini
  - cmd: SET PATH=C:\tools\php;%PATH%
  - cmd: SET PATH=C:\tools\php\ext;%PATH%
  - ps: ($env:Path)
  - ps: new-item c:\composer -itemtype directory
  # Prove file is there
  - ps: (Get-Item c:\tools\php\ext\php_wincache.dll).VersionInfo
#  - cmd: dir /q C:\tools\php\ext
  - cmd: php -i
  - ps: Get-Content C:\Windows\Temp\php_errors.log
# Print permissions of all php extensions
  - cmd: cd C:\tools\php\ext
  - ps: Dir | Get-Acl
  # Install composer
  - cmd: cd /d C:\composer
  - cmd: php -r "readfile('http://getcomposer.org/installer');" | php
  - ps: (Get-Item C:\composer\composer.phar).length
  - ps: "'@php C:\\composer\\composer.phar ' + $([char]37) + '*' | Out-File C:\\composer\\composer.bat -Encoding ASCII"
  - cmd: SET PATH=C:\composer;%PATH%
  # Install Drupal
  - cmd: cd /d C:\projects\
  - cmd: composer create-project -n drupal-composer/drupal-project:8.x-dev
  - cmd: cd /d C:\projects\drupal-project
  - cmd: composer config repositories.drupal composer https://packages.drupal.org/8
  - cmd: composer require drupal/sqlsrv:~1.0
  - cmd: xcopy /S /I /E %cd%\web\modules\contrib\sqlsrv\drivers %cd%\web\drivers
  - ps: "'@php C:\\projects\\drupal-project\\vendor\\drupal\\console\\bin\\drupal ' + $([char]37) + '*' | Out-File C:\\projects\\drupal-project\\web\\drupal.bat -Encoding ASCII"
  - cmd: cd /d C:\projects\drupal-project\web
  - cmd: drupal about
  - cmd: drupal site:install standard --langcode="en" --db-type="sqlsrv" --db-host="localhost\SQL2014" --db-name="mydrupalsite" --db-user="sa" --db-pass="Password12!" --db-port="1433" --site-name="SQL Server Drupal Site" --site-mail="admin@example.com" --account-name="admin" --account-mail="admin@example.com" --account-pass="admin" --no-interaction
  - cmd: drupal about
  - cmd: cd /d C:\projects\drupal-project
  - cmd: cd /d C:\projects\drupal-project\web
  - cmd: drupal module:install simpletest
  - cmd: choco install -y urlrewrite
  - ps: New-WebSite -Name 'MyWebsite' -PhysicalPath 'c:\projects\drupal-project\web' -Force
  - ps: echo 127.0.0.1 www.mysite.com >> %WINDIR%\System32\Drivers\Etc\Hosts
  - ps: Import-Module WebAdministration; Set-ItemProperty 'IIS:\Sites\MyWebsite' -name Bindings -value @{protocol='http';bindingInformation='*:80:www.mysite.com'}
  - ps: SET PATH=%systemroot%\system32\inetsrv\;%PATH%
  - ps: echo Change default anonymous user AUTH to ApplicationPool
  - ps: appcmd set config -section:anonymousAuthentication /username:"" --password
  - ps: echo Setup FAST-CGI configuration
  - ps: appcmd set config /section:system.webServer/fastCGI /+[fullPath='C:\tools\php\php-cgi.exe']
  - ps: echo Setup FACT-CGI handler
  - ps: appcmd set config /section:system.webServer/handlers /+[name='PHP-FastCGI',path='*.php',verb='*',modules='FastCgiModule',scriptProcessor='C:\tools\php\php-cgi.exe',resourceType='Either']
  - ps: iisreset
  - ps: NET START W3SVC
  - ps: wget http://www.mysite.com/
test_script:
- cmd: >-
    cd /d C:\projects\drupal-project
    mkdir c:\testresults\
    php web/core/scripts/run-tests.sh --php php --all --verbose --url "http://www.mysite.com/" --xml c:\testresults\
artifacts:
- path: c:\testresults
  name: Results
